
    const schema = {
  "asyncapi": "2.4.0",
  "info": {
    "title": "Notification Service - Async API Event Contracts",
    "version": "1.0.0",
    "description": "This specification defines the asynchronous event-driven contracts for the Notification Microservice. The service operates strictly as a reactive consumer within the platform's message broker,  subscribing to core domain events to process transactional emails and push notifications  while maintaining absolute loose coupling (NFR-D4).\n"
  },
  "servers": {
    "development": {
      "url": "localhost:5672",
      "protocol": "amqp",
      "description": "Local RabbitMQ development broker"
    },
    "production": {
      "url": "rabbitmq.e-learning.platform:5672",
      "protocol": "amqps",
      "description": "Production RabbitMQ cluster with TLS encryption"
    }
  },
  "channels": {
    "user.events.registered": {
      "subscribe": {
        "summary": "Consume new user registration events for greeting notifications (FR-6.1)",
        "operationId": "onUserRegistered",
        "message": {
          "name": "UserRegistered",
          "title": "User Registered Event",
          "summary": "Emitted atomically by the User Service when a new account is successfully verified.",
          "contentType": "application/json",
          "payload": {
            "type": "object",
            "required": [
              "trace_id",
              "user_id",
              "email",
              "user_name"
            ],
            "properties": {
              "trace_id": {
                "type": "string",
                "format": "uuid",
                "description": "Distributed tracing identifier used to track end-to-end processing latency (NFR-O4).",
                "x-parser-schema-id": "<anonymous-schema-2>"
              },
              "user_id": {
                "type": "string",
                "format": "uuid",
                "description": "The unique decoupled ID of the user generated by the source microservice.",
                "x-parser-schema-id": "<anonymous-schema-3>"
              },
              "email": {
                "type": "string",
                "format": "email",
                "description": "The target recipient email address for transactional greeting.",
                "x-parser-schema-id": "<anonymous-schema-4>"
              },
              "user_name": {
                "type": "string",
                "description": "The display name of the user used for dynamic template parsing.",
                "x-parser-schema-id": "<anonymous-schema-5>"
              }
            },
            "x-parser-schema-id": "<anonymous-schema-1>"
          }
        }
      }
    },
    "payment.events.succeeded": {
      "subscribe": {
        "summary": "Consume successful course payment confirmations to trigger receipt emails (FR-5.2)",
        "operationId": "onPaymentSucceeded",
        "message": {
          "name": "PaymentSucceeded",
          "title": "Payment Succeeded Event",
          "summary": "Emitted by the Payment Service immediately after a financial transaction clears.",
          "contentType": "application/json",
          "payload": {
            "type": "object",
            "required": [
              "trace_id",
              "transaction_id",
              "user_id",
              "email",
              "course_title",
              "amount"
            ],
            "properties": {
              "trace_id": {
                "type": "string",
                "format": "uuid",
                "description": "Distributed tracing identifier (NFR-O4).",
                "x-parser-schema-id": "<anonymous-schema-7>"
              },
              "transaction_id": {
                "type": "string",
                "format": "uuid",
                "description": "Global ledger tracking reference for accountability.",
                "x-parser-schema-id": "<anonymous-schema-8>"
              },
              "user_id": {
                "type": "string",
                "format": "uuid",
                "x-parser-schema-id": "<anonymous-schema-9>"
              },
              "email": {
                "type": "string",
                "format": "email",
                "x-parser-schema-id": "<anonymous-schema-10>"
              },
              "course_title": {
                "type": "string",
                "description": "Premium course name required to fulfill the confirmation template injection.",
                "x-parser-schema-id": "<anonymous-schema-11>"
              },
              "amount": {
                "type": "number",
                "description": "The total transaction volume. Note that fields are audited under encryption rules (NFR-S4).",
                "x-parser-schema-id": "<anonymous-schema-12>"
              }
            },
            "x-parser-schema-id": "<anonymous-schema-6>"
          }
        }
      }
    },
    "progress.events.course_completed": {
      "subscribe": {
        "summary": "Consume 100% course completion events to trigger certificate push alerts (FR-6.3)",
        "operationId": "onCourseCompleted",
        "message": {
          "name": "CourseCompleted",
          "title": "Course Completed Event",
          "summary": "Emitted by the Progress Service when a student completes all core modules.",
          "contentType": "application/json",
          "payload": {
            "type": "object",
            "required": [
              "trace_id",
              "user_id",
              "email",
              "course_id",
              "certificate_uuid"
            ],
            "properties": {
              "trace_id": {
                "type": "string",
                "format": "uuid",
                "x-parser-schema-id": "<anonymous-schema-14>"
              },
              "user_id": {
                "type": "string",
                "format": "uuid",
                "x-parser-schema-id": "<anonymous-schema-15>"
              },
              "email": {
                "type": "string",
                "format": "email",
                "x-parser-schema-id": "<anonymous-schema-16>"
              },
              "course_id": {
                "type": "string",
                "format": "uuid",
                "x-parser-schema-id": "<anonymous-schema-17>"
              },
              "certificate_uuid": {
                "type": "string",
                "format": "uuid",
                "description": "Unique secure identifier of the newly generated digital credential.",
                "x-parser-schema-id": "<anonymous-schema-18>"
              }
            },
            "x-parser-schema-id": "<anonymous-schema-13>"
          }
        }
      }
    }
  },
  "components": {
    "messages": {
      "UserRegisteredEvent": "$ref:$.channels.user.events.registered.subscribe.message",
      "PaymentSucceededEvent": "$ref:$.channels.payment.events.succeeded.subscribe.message",
      "CourseCompletedEvent": "$ref:$.channels.progress.events.course_completed.subscribe.message"
    }
  },
  "x-parser-spec-parsed": true,
  "x-parser-api-version": 3,
  "x-parser-spec-stringified": true
};
    const config = {"show":{"sidebar":true},"sidebar":{"showOperations":"byDefault"}};
    const appRoot = document.getElementById('root');
    AsyncApiStandalone.render(
        { schema, config, }, appRoot
    );
  